version: '3.8'

services:
  # Servicio de la aplicación
  app:
    build: .
    container_name: ghr-app
    ports:
      - "4321:4321"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go_human_resources_db
      - PORT=4321
    restart: always
    command: sh -c '/app/wait-for-postgres.sh && ./app'
    networks:
      - ghr-network
    volumes:
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro

  # Servicio de base de datos
  db:
    image: postgres:15-alpine
    container_name: ghr-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_human_resources_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - ghr-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ghr-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
